name: Generate Snake Animation

on:
  schedule:
    # A animação será atualizada a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório
      - uses: actions/checkout@v2

      # Configura o Python para rodar o script
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

    

      # Gera a animação Snake
      - run: |
          python3 generate_snake.py

      # Faz o upload da animação gerada para o GitHub Pages
      - name: Upload Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out

  
